name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: plugins/safe-local-files
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: plugins/safe-local-files/go.mod
          cache-dependency-path: plugins/safe-local-files/go.sum
      - name: Go tests
        run: go test ./...
      - name: Go vet
        run: go vet ./...
